### PR TITLE
Remove thank you emails for stripe donations

### PR DESCRIPTION
**Pull request by patjouk**
Related issue: mozilla/donate.mozilla.org#2156

Since we won't be using stripe with sawmill, I removed the stripe dependency.

**Do not merge now:** I need to sync with Will when we will deploy this.

### CODE REVIEW

**Comment by alanmoo** [comment]
Any suggestions on how to test this?

**Review by Pomax — APPROVED** [review]
looks like exactly what's needed

**Comment by patjouk** [comment]
For testing, the usual: deploy on staging and see how it goes using donate staging.
For rolling out: I would go with activating both features first, push sawmill to prod and apply the changes to stripe, and finally test it in prod with a donation. I will sync with folks from fundraising to see when people don't usually donate to minimize the impact of something going wrong.

**Comment by patjouk** [comment]
Merging now to test on staging, will promote to prod tomorrow at 12am ET.

**Pull request merged**
