### PR TITLE
check if this is a thundebird donation before attempting a fallback f…

### LINKED ISSUE #71: Order of email check looks like a bug
This looks highly suspect: https://github.com/mozilla/sawmill/blob/master/worker/stripe_charge_succeeded.js#L71-L76

It looks like we check for the localized email before checking for thunderbird. So this also looks like donations to thunderbird not in English probably get a mozilla and not thunderbird email.

@cadecairos

### PR DESCRIPTION
**Pull request by cadecairos**
…or l10n support

Fixes #71 

R? @ScottDowne

### CODE REVIEW

**Comment by ScottDowne** [comment]
@cadecairos looks like travis is angry about something. Is it legit?

**Comment by cadecairos** [comment]
It's passing for me locally. not sure what's up

**Comment by ScottDowne** [comment]
@cadecairos I'm no expert on this repos tests, and you're probably the expert on how legit this failure is. So if it's passing locally, you can be the judge. The changes don't look to be connected to the travis errors.

**Comment by cadecairos** [comment]
This is just a guess, but it looks like the test tries to force a hatchet error by setting the hatchet queue URL to "127.0.0.1" - I wonder if the build box's loopback interface is causing requests to hang now for some reason. 

but otherwise, I agree that this failure is unrelated to my changes.

**Comment by ScottDowne** [comment]
k, well, for what it's worth I'm fine with R+ on this.

**Pull request merged**
