### PR TITLE
mailroom version bump to 0.3.7

### PR DESCRIPTION
**Pull request by secretrobotron**

### CODE REVIEW

**Comment by secretrobotron** [comment]
@cadecairos r?

**Comment by secretrobotron** [comment]
I don't.. *think* this makes any sense... because mailroom is already at 0.3.7...
@jbuck

**Comment by cadecairos** [comment]
what's going on here

**Comment by secretrobotron** [comment]
I don't k..... I don't know. :cat: 
Probably just ... close.

**Pull request closed without merging**
