### PR TITLE
upgraded webmaker-mailroom to 0.3.8

### PR DESCRIPTION
**Pull request by secretrobotron**

### CODE REVIEW

**Comment by secretrobotron** [comment]
Needs 0.3.8 to be on npm. cc @jbuck

**Comment by secretrobotron** [comment]
Contributes to fixing https://github.com/mozilla/id.webmaker.org/issues/274

**Comment by secretrobotron** [comment]
webmaker-mailroom 0.3.8 published on npm. woot.
@cadecairos r?

**Comment by cadecairos** [comment]
R+

**Pull request merged**
