### PR TITLE
Update webmaker-mailroom to version 0.3.13

### PR DESCRIPTION
**Pull request by alicoding**

### CODE REVIEW

**Comment by alicoding** [comment]
@secretrobotron r?

We should merge this after we publish webmaker-mailroom to npm, but I guess we need help from either @cadecairos or @jbuck to do this since I don't have publish right to that package, yet.

**Comment by jbuck** [comment]
@alicoding I added you to npm owner for webmaker-mailroom. I dunno what @secretrobotron npm username is

**Comment by alicoding** [comment]
@secretrobotron I just publish this to npm, so we should merge this soon to test again.

**Comment by secretrobotron** [comment]
r+

**Pull request merged**
