### PR TITLE
Add Migration email logic

### LINKED ISSUE #44: Check for flag on token login emails to trigger a switch to the migration email template
From https://github.com/mozilla/id.webmaker.org/issues/109

Need to check for a flag on token login emails to trigger a switch to the migration email template. This will happen when migrating users from passwordless login on new id.webmaker.org.

### PR DESCRIPTION
**Pull request by cadecairos**
Fixes #44

### CODE REVIEW

**Comment by cadecairos** [comment]
@secretrobotron Need to land and tag mozilla/webmaker-mailroom#28 for this to pass travis

**Comment by secretrobotron** [comment]
:+1: Looks alright. Just waiting on a glance from @vazquez on https://github.com/mozilla/webmaker-mailroom/pull/28 to continue.

**Comment by secretrobotron** [comment]
Unlocked!

**Comment by cadecairos** [comment]
@secretrobotron travis is green, shall we merge?

**Comment by secretrobotron** [comment]
Do it.

**Pull request merged**
